---
swagger: "2.0"
info:
  description: "API service for Saphron nan.ai"
  version: "1.0.0"
  title: "Saphron Nan.ai API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "tech@saphron.asia"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "saphron-nanai.swagger.io"
basePath: "/v1"
tags:
- name: "chatfuel"
  description: "Chatfuel integration endpoints"
- name: "reports"
  description: "Access to back office reports"
schemes:
- "https"
paths:
  /chatfuel/agents/validate:
    post:
      tags:
      - "chatfuel"
      summary: "Validate nan.ai sales agent FB messenger account"
      description: ""
      operationId: "chatfuelAgentsValidate"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            field:
              type: "string"
            messenger_user_id:
              type: "string"
      responses:
        200:
          description: "Registered user"
          schema:
            type: "object"
            properties:
              redirect_to_blocks:
                type: "array"
                items: 
                  type: "string"
        405:
          description: "Invalid input"
      security:
      - api_key: []
  /chatfuel/agents/register:
    post:
      tags:
      - "chatfuel"
      summary: "Register new nan.ai sales agent"
      description: ""
      operationId: "chatfuelAgentsRegister"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            name:
              type: "string"
            agent_code:
              type: "string"
            cp_number:
              type: "string"
            messenger_user_id:
              type: "string"
            agent_fb_name:
              type: "string"
      responses:
        200:
          description: "Successful registration"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
        405:
          description: "Invalid input"
      security:
      - api_key: []
  /chatfuel/agents/updateFBName:
    post:
      tags:
      - "chatfuel"
      summary: "Update angent's FB name"
      description: ""
      operationId: "chatfuelAgentUpdateFBName"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            messenger_user_id:
              type: "string"
            agent_fb_name:
              type: "string"
      responses:
        200:
          description: "Successful update"
          schema:
            type: "object"
            properties:
              redirect_to_blocks:
                type: "array"
                items: 
                  type: "string"
        405:
          description: "Invalid input"
      security:
      - api_key: []
  /chatfuel/policies/validate:
    post:
      tags:
      - "chatfuel"
      summary: "Check if policy is valid"
      description: ""
      operationId: "chatfuelPoliciesValidate"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            messenger_user_id:
              type: "string"
            field:
              type: "string"
            insuredFN:
              type: "string"
      responses:
        200:
          description: "Successful validation"
          schema:
            type: "object"
            properties:
              set_attributes:
                type: "object"
                properties: 
                  validInput:
                    type: "boolean"
        405:
          description: "Invalid input"
      security:
      - api_key: []
  /chatfuel/policies/enroll:
    post:
      tags:
      - "chatfuel"
      summary: "Enroll a policy"
      description: ""
      operationId: "chatfuelPoliciesEnroll"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            messenger_user_id:
              type: "string"
            insuredFN:
              type: "string"
            insuredMI:
              type: "string"
            insuredLN:
              type: "string"
            insuredMobile:
              type: "string"
            insuredBirthdate:
              type: "string"
            productID:
              type: "string"
            product:
              type: "string"
            returnStub:
              type: "string"
            returnStub2:
              type: "string"
            returnStub3:
              type: "string"
            agentPO:
              type: "string"
            agentUnit:
              type: "string"
            insuredEffectivity:
              type: "string"
            headCount:
              type: "integer"
      responses:
        200:
          description: "Successful enrollment"
          schema:
            type: "object"
            properties:
              set_attributes:
                type: "object"
                properties: 
                  accuracyFactor:
                    type: "number"
        405:
          description: "Invalid input"
      security:
      - api_key: []
  /chatfuel/policies/calculate:
    post:
      tags:
      - "chatfuel"
      summary: "Calculate policy premium"
      description: ""
      operationId: "chatfuelPoliciesCalculate"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            product:
              type: "string"
      responses:
        200:
          description: "Successful update"
          schema:
            type: "object"
            properties:
              set_attributes:
                type: "object"
                properties: 
                  totalPrice:
                    type: "number"
        405:
          description: "Invalid input"
      security:
      - api_key: []
  /reports/generate:
    get:
      tags:
      - "reports"
      summary: "Returns back office report"
      description: ""
      operationId: "reportsGenerate"
      parameters: []
      responses:
        200:
          description: "CSV report"
          content:
            application/csv:
              schema:
                type: string
                format: binary
      security:
      - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  PolicyForm:
    type: "object"
    properties:
      messenger_user_id:
        type: "string"
      insuredFN:
        type: "string"
      insuredMI:
        type: "string"
      insuredLN:
        type: "string"
      insuredMobile:
        type: "string"
      insuredBirthdate:
        type: "string"
      productID:
        type: "string"
      product:
        type: "string"
      returnStub:
        type: "string"
      returnStub2:
        type: "string"
      returnStub3:
        type: "string"
      agentPO:
        type: "string"
      agentUnit:
        type: "string"
      insuredEffectivity:
        type: "string"
      headCount:
        type: "integer"

